inherits = "autumn"
"ui.background" = {}
"ui.gutter" = { bg = {} }
"ui.linenr" = { bg = {} }
"ui.linenr.selected" = { bg = {} }

"markup.heading" = "orange"
"markup.list" = "yellow"
"markup.bold" = { fg = "orange", modifiers = ["bold"] }
"markup.italic" = { fg = "orange", modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.raw.block" = "orange"
"markup.link.url" = "blue"
"markup.link.text" = "yellow"
"markup.link.label" = "green"