#!/bin/bash
set -euo pipefail # Exit on error, unset variable or pipe fail

if uname != "Darwin"; then echo "Darwin only" && exit 1; fi

# Computer naming
scutil --set ComputerName mac
scutil --set LocalHostName mac

# # Disable wake by network
# sudo pmset -a womp 0
# # Disable wake by other devices using the same iCloud id
# sudo pmset -a proximitywake 0
# # Disable auto update, auto backup when sleeping
# sudo pmset -a powernap 0
# # Enable "full light - half light - off" screen transition, when going to sleep
# sudo pmset -a halfdim 1

# Screensaver password
defaults write com.apple.screensaver askForPassword -int 1
defaults write com.apple.screensaver askForPasswordDelay -int 10
# Expose hidden files in Library
defaults write com.apple.finder AppleShowAllFiles -bool true
chflags nohidden ~/Library
# Show all extensions
defaults write NSGlobalDomain AppleShowAllExtensions -bool true
# No default saving to iCloud
defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false
# No crash reporting popup
defaults write com.apple.CrashReporter DialogType none
# Screenshots
defaults write com.apple.screencapture type jpg
# BUG: following does not work yet
defaults write com.apple.screencapture location ~/Pictures
# Disable automatic capitalization
defaults write -g NSAutomaticCapitalizationEnabled -bool false
# Jump to the spot that's clicked on the scroll bar
defaults write -g AppleScrollerPagingBehavior -bool true
# Allow Finder quitting via ⌘Q
defaults write com.apple.finder QuitMenuItem -bool true
# Show path bar, and layout as multi-column
defaults write com.apple.finder ShowPathbar -bool true
defaults write com.apple.finder FXPreferredViewStyle -string clmv
# Activity Monitor sorts by CPU usage
defaults write com.apple.ActivityMonitor SortColumn -string CPUUsage
defaults write com.apple.ActivityMonitor SortDirection -int 0
# Avoid creating .DS_Store files on USB or network volumes
defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
# Disable personalized advertising
defaults com.apple.AdLib forceLimitAdTracking -bool true
defaults com.apple.AdLib allowApplePersonalizedAdvertising -bool false
defaults com.apple.AdLib allowIdentifierForAdvertising -bool false

# More behavior
defaults write com.apple.dock expose-group-apps -bool true
defaults write com.apple.WindowManager EnableStandardClickToShowDesktop -bool false
defaults write NSGlobalDomain KeyRepeat -int 2 # 120, 90, 60, 30, 12, 6, 2
defaults write NSGlobalDomain InitialKeyRepeat -int 15 # 120, 94, 68, 35, 25, 15
defaults write NSGlobalDomain AppleWindowRounding -int 0
defaults write NSGlobalDomain NSAutomaticWindowAnimationsEnabled -bool false
defaults write com.apple.dock autohide -bool true
defaults write com.apple.dock tilesize -int 32
defaults write com.apple.dock launchanim -int 0

# Safari
defaults write com.apple.Safari UniversalSearchEnabled -bool false
defaults write com.apple.Safari SuppressSearchSuggestions -bool true
defaults write com.apple.Safari SendDoNotTrackHTTPHeader -bool true
defaults write com.apple.Safari AutoOpenSafeDownloads -bool false
defaults write com.apple.Safari IncludeDevelopMenu -bool true
defaults write com.apple.Safari IncludeInternalDebugMenu -bool true
defaults write com.apple.Safari WebKitDeveloperExtras -bool true
defaults write com.apple.Safari WebKitDeveloperExtrasEnabledPreferenceKey -bool true
defaults write com.apple.Safari "com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled" -bool true

# Set up a blocklist of malicious hosts if one isn't present
[ $(wc -l < /etc/hosts | bc) -lt 1000 ] && curl https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts | tee -a /etc/hosts

echo "Defaults have been set, please reboot to ensure they all take effect."
exit 0
