#!/bin/bash
set -euo pipefail # Exit on error, unset variable or pipe fail

if uname != "Darwin"; then echo "Darwin only" && exit 1; fi

if ! command -v brew &> /dev/null; then
    echo "Homebrew not found, installing homebrew."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi

eval "export HOMEBREW_NO_ANALYTICS=1"
eval "export HOMEBREW_NO_INSECURE_REDIRECT=1"
eval "export HOMEBREW_CASK_OPTS=--require-sha"

brew bundle --file=~/dotfiles/setup/brewfile
[ -f "~/dotfiles/setup/private-brewfile" ] && brew bundle --file=~/dotfiles/setup/private-brewfile

echo "Cleaning up..."
brew autoremove
brew cleanup
echo "Homebrew packages have been installed!"

exit 0
