theme = "zigs-and-zags"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
V = ["goto_first_nonwhitespace", "extend_to_line_end"]

[editor.cursor-shape]
insert = "underline"

[editor.soft-wrap]
enable = true

