[language-server.from-racket-bin]
command = "racket"
args = ["-l", "racket-langserver"]

[[language]]
name = "scheme"
scope = "source.scheme"
file-types = ["rkt", "scm"]
indent = { tab-width = 2, unit = "  " }
formatter = { command = "racket-fixw" }
language-servers = [ "from-racket-bin" ]
